[project]
name = "SIMONE"
version = "0.1.0"
description = "My thesis work contributes an automated extraction approach that turns heterogeneous catalysis research data into structured, reusable, and FAIR-compliant datasets."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.136.1",
    "ollama>=0.6.2",
    "pydantic>=2.13.4",
    "rdflib-neo4j>=1.1",
]
